// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psxpoxxjiozvobkiwquh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzeHBveHhqaW96dm9ia2l3cXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjQ1OTgsImV4cCI6MjA2MjA0MDU5OH0.PfzV-uOtY4Qq8WimF-EGxGiSykBVLKpEudNz5HmBbEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);